# Generated by Django 2.2.7 on 2020-07-27 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='catogory',
            new_name='category',
        ),
        migrations.AddField(
            model_name='note',
            name='body',
            field=models.TextField(default='Who sat and watch my Infantness', max_length=500),
        ),
        migrations.AlterField(
            model_name='note',
            name='author',
            field=models.CharField(blank=True, help_text='If note is composed by youuse your name(optional)', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
