# Generated by Django 2.2.7 on 2020-07-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20200727_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='body',
            field=models.TextField(default='Who sat and watch my Infantness', max_length=1000),
        ),
    ]
